name: Daily Ceneo Reviews Scraper

on:
  schedule:
    - cron: "5 5 * * *" # 05:05 UTC daily (~07:05 Prague)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm ci || npm i

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        # ✅ make sure the path matches your file name
        run: node scripts/scrape-ceneo-reviews.cjs

      - name: Commit changes (if any)
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/ceneo_reviews_pl.json
          git commit -m "Update ceneo_reviews_pl.json" || echo "No changes to commit"
          git push
