name: Daily Ceneo Reviews Scraper

on:
  schedule:
    - cron: "5 5 * * *"   # runs daily at 05:05 UTC (≈07:05 Prague time)
  workflow_dispatch:      # allow manual runs from Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm ci || npm i

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        run: node scripts/scrape-ceneo-reviews.cjs

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data/reviews.json
            git commit -m "chore: update Ceneo reviews ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          else
            echo "No changes to commit."
          fi
